"""Initial migration

Revision ID: 9558ff7c7c32
Revises: 
Create Date: 2025-03-01 22:47:01.119423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9558ff7c7c32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=26),
               existing_nullable=False)
    op.alter_column('layers', 'project_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=26),
               existing_nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=26),
               existing_nullable=False)
    op.alter_column('projects', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'id',
               existing_type=sa.String(length=26),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('layers', 'project_id',
               existing_type=sa.String(length=26),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('layers', 'id',
               existing_type=sa.String(length=26),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
